#!/bin/bash -e
exec 1>&2
myerr(){
	echo -e "\033[31m\033[1mcommit-msg: ERROR: $@\033[0m"
}
mymsg(){
	echo commit-msg: $@
}
if make -q; then 
	mymsg All Makefile targets are up to date.
else
	myerr 'Outdated Makefile targets found. run "make".'
	exit 1
fi
if git diff --quiet; then
	mymsg No git unstaged changes found.
else
	myerr 'Unstaged changes found. run "git add".'
	exit 1
fi
msg="commit-msg approval for `whoami` on `date '+%Y.%m.%d-%H:%M:%S'`"
echo $msg >>$1
mymsg Success
exit 0