#!/bin/bash -e
exec 1>&2
myerr(){
	echo -e "\033[31m\033[1mpre-commit: ERROR: $@\033[0m"
}
if make -q; then
	true
else
	myerr 'Outdated Makefile targets found. run "make".'
	exit 1
fi
if git diff --quiet; then
	true
else
	myerr 'Unstaged changes found. run "git add".'
	exit 1
fi
exit 0