#!/bin/bash
set -e
myerr(){
        echo -e "\033[31m\033[1mpre-commit: ERROR: $@\033[0m"
        exit 1
}
scripts/makechangelog >CHANGELOG.txt
if diff -q CHANGELOG.txt CHANGELOG.md >/dev/null 2>&1; then
    rm CHANGELOG.txt
else
    rm CHANGELOG.txt
    myerr "CHANGELOG.md is not up to date. Do 'make CHANGELOG.md'."
fi

if make -q; then
        true
else
        myerr 'Outdated Makefile targets found. run "make".'
fi
if git diff --quiet; then
        true
else
        myerr 'Unstaged changes found. run "git add".'
fi
vername=`grep 'version=' setup.py | sed -n "s/.*version='\\([0-9.]*\\)'.*,/v\\1/p"`
if [ $(git tag -l "$vername") ]; then
    myerr "Tag $vername already exists. Either update the version number in setup.py, or delete the tag."
fi
git tag -a $vername -m 'Version tagged by make-pypi-release script.' && git push origin $vername
