#!/bin/bash
export PATH=$OPATH
fn=${3%.*}
pyp=$fn.pyptex
gld=$fn.pyptexgold
pdf=$fn.pdf
if cmp -s $pyp $gld && [ -f $pdf ]; then 
	echo "$pdf is cached"
	touch $pdf
else
	(cmp -s $pyp $gld && echo "Reusing $gld") || (cp $pyp $gld && echo "Updating $gld")
	pdflatex $1 $2 $gld
fi

